#!/usr/bin/with-contenv bash

printf "[Interface]\nPrivateKey = " > /etc/wireguard/wg0.conf

if [ -z $WG_PRIVKEY ]; then
	pubk=$(wg genkey | tee -a /etc/wireguard/wg0.conf | wg pubkey)
else
	echo $WG_PRIVKEY >> /etc/wireguard/wg0.conf
	pubk=$(echo $WG_PRIVKEY | wg pubkey)
fi
printf "ListenPort = 51820\n\n" >> /etc/wireguard/wg0.conf


echo The public key is: $pubk
